project:
  type: website

website:
  title: "BenqBlog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Benamollo
      - icon: twitter
        href: https://twitter.com/kampspatial
      - icon: facebook
        href: https://facebook.com/kampspatial
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

